import { SourceCapability, SourceId } from "@/agent/core/types";

export const SOURCE_CAPABILITIES: Record<SourceId, SourceCapability> = {
  tiktok_creative_center: {
    id: "tiktok_creative_center",
    mode: "search_backed",
    title: "TikTok Creative Center",
    primaryUrl: "https://ads.tiktok.com/business/creativecenter/top-products/pc/en",
    requiresAuth: false,
    notes: "Primary source for current TikTok product momentum.",
  },
  tiktok_shop_search: {
    id: "tiktok_shop_search",
    mode: "search_backed",
    title: "TikTok Shop search",
    primaryUrl: "https://www.tiktok.com/shop",
    requiresAuth: false,
    notes: "Search-backed validation for what is trending on TikTok Shop right now.",
  },
  tiktok_hashtag_search: {
    id: "tiktok_hashtag_search",
    mode: "search_backed",
    title: "TikTok hashtag search",
    primaryUrl: "https://ads.tiktok.com/business/creativecenter/inspiration/popular/hashtag/pc/en",
    requiresAuth: false,
    notes: "Search-backed validation for hashtag-driven product momentum.",
  },
  tiktok_made_me_buy_it_search: {
    id: "tiktok_made_me_buy_it_search",
    mode: "search_backed",
    title: "TikTok made me buy it search",
    primaryUrl: "https://www.tiktok.com/tag/tiktokmademebuyit",
    requiresAuth: false,
    notes: "Search-backed validation for products that repeatedly show up in buy-it-now content.",
  },
  shopify_tiktok_products: {
    id: "shopify_tiktok_products",
    mode: "search_backed",
    title: "Shopify TikTok products",
    primaryUrl: "https://www.shopify.com/blog/tiktok-products",
    requiresAuth: false,
    notes: "Supporting commerce source for current product demand corroboration.",
  },
  shopify_tiktok_trends: {
    id: "shopify_tiktok_trends",
    mode: "search_backed",
    title: "Shopify TikTok trends",
    primaryUrl: "https://www.shopify.com/blog/tiktok-trends",
    requiresAuth: false,
    notes: "Supporting commerce source for current product-category corroboration.",
  },
  cj_winning_products: {
    id: "cj_winning_products",
    mode: "search_backed",
    title: "CJ winning products",
    primaryUrl: "https://cjdropshipping.com/blogs/winning-products/Best-Trending-Dropshipping-Products-for-May-2026",
    requiresAuth: false,
    notes: "Supplier-side source that still needs current TikTok corroboration.",
  },
  cj_tiktok_products: {
    id: "cj_tiktok_products",
    mode: "search_backed",
    title: "CJ TikTok products",
    primaryUrl: "https://cjdropshipping.com/blogs/winning-products/TikTok-Viral-products-2026",
    requiresAuth: false,
    notes: "Supplier-side source focused on TikTok-friendly products.",
  },
};